export const ChallengeMarketABI = [
  {
    name: "createMatch",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "playerA", type: "address" },
      { name: "playerB", type: "address" },
      { name: "startTime", type: "uint64" },
      { name: "expiryTime", type: "uint64" },
      { name: "baseCutBps", type: "uint16" },
      { name: "winnerBonusBps", type: "uint16" },
      { name: "copyFeeBps", type: "uint16" },
    ],
    outputs: [{ name: "matchId", type: "uint256" }],
  },
  {
    name: "placeBet",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "side", type: "uint8" },
      { name: "amount", type: "uint256" },
      { name: "copiedFrom", type: "address" },
    ],
    outputs: [{ name: "betId", type: "uint256" }],
  },
  {
    name: "submitResult",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "winner", type: "uint8" },
    ],
    outputs: [],
  },
  {
    name: "finalizeAfterTimeout",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "resolveDispute",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "winner", type: "uint8" },
    ],
    outputs: [],
  },
  {
    name: "expireMatch",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "claimBet",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "betId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "MatchCreated",
    type: "event",
    inputs: [
      { indexed: true, name: "matchId", type: "uint256" },
      { indexed: true, name: "host", type: "address" },
      { indexed: true, name: "playerA", type: "address" },
      { indexed: false, name: "playerB", type: "address" },
      { indexed: false, name: "startTime", type: "uint64" },
      { indexed: false, name: "expiryTime", type: "uint64" },
      { indexed: false, name: "baseCutBps", type: "uint16" },
      { indexed: false, name: "winnerBonusBps", type: "uint16" },
      { indexed: false, name: "copyFeeBps", type: "uint16" },
    ],
    anonymous: false,
  },
  {
    name: "BetPlaced",
    type: "event",
    inputs: [
      { indexed: true, name: "betId", type: "uint256" },
      { indexed: true, name: "matchId", type: "uint256" },
      { indexed: true, name: "bettor", type: "address" },
      { indexed: false, name: "side", type: "uint8" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "copiedFrom", type: "address" },
    ],
    anonymous: false,
  },
  {
    name: "ResultSubmitted",
    type: "event",
    inputs: [
      { indexed: true, name: "matchId", type: "uint256" },
      { indexed: true, name: "player", type: "address" },
      { indexed: false, name: "winner", type: "uint8" },
    ],
    anonymous: false,
  },
  {
    name: "MatchResolved",
    type: "event",
    inputs: [
      { indexed: true, name: "matchId", type: "uint256" },
      { indexed: false, name: "winner", type: "uint8" },
      { indexed: false, name: "losingPool", type: "uint256" },
      { indexed: false, name: "remainingLosingPool", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    name: "MatchDisputed",
    type: "event",
    inputs: [
      { indexed: true, name: "matchId", type: "uint256" },
      { indexed: false, name: "playerAWinner", type: "uint8" },
      { indexed: false, name: "playerBWinner", type: "uint8" },
    ],
    anonymous: false,
  },
  {
    name: "MatchExpired",
    type: "event",
    inputs: [
      { indexed: true, name: "matchId", type: "uint256" },
      { indexed: false, name: "totalPool", type: "uint256" },
      { indexed: false, name: "expiryFee", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    name: "BetClaimed",
    type: "event",
    inputs: [
      { indexed: true, name: "betId", type: "uint256" },
      { indexed: false, name: "payout", type: "uint256" },
      { indexed: false, name: "copyFee", type: "uint256" },
    ],
    anonymous: false,
  },
] as const;
